# Generated by Django 4.1.5 on 2023-01-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raca',
            old_name='tag',
            new_name='raca',
        ),
    ]
